# Generated by Django 5.2 on 2025-04-06 16:19

from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=core.utils.generate_id,
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("institution", models.CharField(max_length=100)),
                ("purpose", models.TextField()),
                ("visit_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
